from __future__ import annotations

import copy
from collections import Counter
from typing import Any

from .query_contract import get_query_discovery_metadata

STABILITY_LEVELS = ("stable", "beta", "experimental")
SIDE_EFFECT_LEVELS = ("read_only", "local_state_mutating", "live_side_effecting")


def _capability(
    name: str,
    *,
    domain: str,
    description: str,
    stability: str,
    side_effect_level: str,
    manager_method: str | None = None,
    api_command: str | None = None,
    flat_command: str | None = None,
    requires: list[str] | None = None,
    capability_version: str = "v1",
) -> dict[str, Any]:
    entrypoints: dict[str, str] = {}
    if manager_method:
        entrypoints["manager_method"] = manager_method
    if api_command:
        entrypoints["api_command"] = api_command
    if flat_command:
        entrypoints["flat_command"] = flat_command
    payload = {
        "name": name,
        "capability_version": capability_version,
        "domain": domain,
        "description": description,
        "stability": stability,
        "side_effect_level": side_effect_level,
        "entrypoints": entrypoints,
        "requires": list(requires or []),
    }
    query_metadata = get_query_discovery_metadata(name)
    if query_metadata is not None:
        payload["query_metadata"] = query_metadata
    return payload


_CAPABILITY_REGISTRY: list[dict[str, Any]] = [
    _capability(
        "runtime.capabilities",
        domain="runtime",
        description="List provider-facing capabilities and grading metadata.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.capabilities",
        api_command="capabilities",
        flat_command="tdx-capabilities",
    ),
    _capability(
        "runtime.health",
        domain="runtime",
        description="Collect structured provider health diagnostics.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.health",
        api_command="health",
        flat_command="tdx-health",
        requires=["windows_runtime_probe"],
    ),
    _capability(
        "runtime.doctor",
        domain="runtime",
        description="Translate provider health state into findings and recommended actions.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.doctor",
        api_command="doctor",
        flat_command="tdx-doctor",
        requires=["windows_runtime_probe"],
    ),
    _capability(
        "market.snapshot",
        domain="market",
        description="Fetch market snapshot fields for a stock.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.snapshot",
        api_command="snapshot",
        flat_command="tdx-data-snapshot",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.market_snapshot",
        domain="market",
        description="Fetch market-wide snapshot style data for a stock.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.market_snapshot",
        api_command="market-snapshot",
        flat_command="tdx-data-market-snapshot",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.kline",
        domain="market",
        description="Fetch kline series data.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.kline",
        api_command="kline",
        flat_command="tdx-data-kline",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.full_tick",
        domain="market",
        description="Fetch full tick data.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.full_tick",
        api_command="full-tick",
        flat_command=None,
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.stock_info",
        domain="market",
        description="Fetch static stock info fields.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.stock_info",
        api_command="stock-info",
        flat_command="tdx-data-stock-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.more_info",
        domain="market",
        description="Fetch extended stock metadata.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.more_info",
        api_command="more-info",
        flat_command="tdx-data-more-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.cb_info",
        domain="market",
        description="Fetch convertible bond metadata.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="market.cb_info",
        api_command="cb-info",
        flat_command="tdx-data-cb-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.stock_list",
        domain="meta",
        description="List securities in a market.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.stock_list",
        api_command="stock-list",
        flat_command="tdx-data-stock-list",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.sector_list",
        domain="meta",
        description="List TongDaXin sectors.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.sector_list",
        api_command="sector-list",
        flat_command="tdx-data-sector-list",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.sector_stocks",
        domain="meta",
        description="List securities inside a TongDaXin sector.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.sector_stocks",
        api_command="sector-stocks",
        flat_command="tdx-data-sector-stocks",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.gb_info",
        domain="meta",
        description="Fetch share capital change data.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.gb_info",
        api_command="gb-info",
        flat_command="tdx-data-gb-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.gp_one_data",
        domain="meta",
        description="Fetch point-in-time stock data fields.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.gp_one_data",
        api_command="gp-one",
        flat_command="tdx-data-gp-one",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.divid_factors",
        domain="meta",
        description="Fetch dividend and split factors.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.divid_factors",
        api_command="divid-factors",
        flat_command="tdx-data-divid-factors",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.ipo_info",
        domain="meta",
        description="Fetch IPO metadata.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="meta.ipo_info",
        api_command="ipo-info",
        flat_command="tdx-data-ipo-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "financial.financial_data",
        domain="financial",
        description="Fetch professional financial data by range.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="financial.financial_data",
        api_command="financial-data",
        flat_command="tdx-data-financial",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "financial.financial_data_by_date",
        domain="financial",
        description="Fetch professional financial data by report date.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="financial.financial_data_by_date",
        api_command="financial-data-by-date",
        flat_command="tdx-data-financial-by-date",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "transaction.stock_transaction_data",
        domain="transaction",
        description="Fetch stock transaction statistics by range.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="transaction.stock_transaction_data",
        api_command="stock-transaction-data",
        flat_command="tdx-data-stock-transaction",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "transaction.stock_transaction_data_by_date",
        domain="transaction",
        description="Fetch stock transaction statistics by date.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="transaction.stock_transaction_data_by_date",
        api_command="stock-transaction-data-by-date",
        flat_command="tdx-data-stock-transaction-by-date",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "transaction.sector_transaction_data",
        domain="transaction",
        description="Fetch sector transaction statistics by range.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="transaction.sector_transaction_data",
        api_command="sector-transaction-data",
        flat_command="tdx-data-sector-transaction",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "transaction.sector_transaction_data_by_date",
        domain="transaction",
        description="Fetch sector transaction statistics by date.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="transaction.sector_transaction_data_by_date",
        api_command="sector-transaction-data-by-date",
        flat_command="tdx-data-sector-transaction-by-date",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "transaction.market_transaction_data",
        domain="transaction",
        description="Fetch market transaction statistics by range.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="transaction.market_transaction_data",
        api_command="market-transaction-data",
        flat_command="tdx-data-market-transaction",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "transaction.market_transaction_data_by_date",
        domain="transaction",
        description="Fetch market transaction statistics by date.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="transaction.market_transaction_data_by_date",
        api_command="market-transaction-data-by-date",
        flat_command="tdx-data-market-transaction-by-date",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.refresh_cache",
        domain="runtime",
        description="Refresh TongDaXin runtime cache.",
        stability="stable",
        side_effect_level="local_state_mutating",
        manager_method="refresh_cache",
        api_command="refresh-cache",
        flat_command="tdx-refresh-cache",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.trading_dates",
        domain="runtime",
        description="Fetch trading dates.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="runtime.trading_dates",
        api_command="trading-dates",
        flat_command="tdx-get-trading-dates",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.refresh_kline",
        domain="runtime",
        description="Refresh historical kline cache for symbols.",
        stability="stable",
        side_effect_level="local_state_mutating",
        manager_method="runtime.refresh_kline",
        api_command="refresh-kline",
        flat_command="tdx-refresh-kline",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.download_file",
        domain="runtime",
        description="Download provider-side files from TongDaXin runtime.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="runtime.download_file",
        api_command="download-file",
        flat_command="tdx-download-file",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.send_warn",
        domain="runtime",
        description="Send warn messages back to TongDaXin client.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="runtime.send_warn",
        api_command="send-warn",
        flat_command="tdx-send-warn",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "subscription.subscribe_hq",
        domain="subscription",
        description="Run one-shot symbol subscription through a temporary runtime session.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.subscription_subscribe",
        api_command="subscription-subscribe",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "subscription.unsubscribe_hq",
        domain="subscription",
        description="Run one-shot symbol unsubscription through a temporary runtime session.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.subscription_unsubscribe",
        api_command="subscription-unsubscribe",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "subscription.get_subscribe_hq_stock_list",
        domain="subscription",
        description="List symbols from a one-shot temporary runtime subscription session.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.subscription_list",
        api_command="subscription-list",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.open_subscription_session",
        domain="runtime",
        description="Open a persistent subscription session.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="runtime.open_subscription_session",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.subscribe_hq",
        domain="runtime",
        description="Subscribe symbols inside an open runtime subscription session.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="runtime.subscribe_hq",
        requires=["native_windows_python", "tqcenter", "subscription_session"],
    ),
    _capability(
        "runtime.unsubscribe_hq",
        domain="runtime",
        description="Unsubscribe symbols inside an open runtime subscription session.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="runtime.unsubscribe_hq",
        requires=["native_windows_python", "tqcenter", "subscription_session"],
    ),
    _capability(
        "runtime.get_subscribe_hq_stock_list",
        domain="runtime",
        description="List currently subscribed symbols inside an open runtime subscription session.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="runtime.get_subscribe_hq_stock_list",
        requires=["native_windows_python", "tqcenter", "subscription_session"],
    ),
    _capability(
        "block.user_sectors",
        domain="block",
        description="List custom TongDaXin sectors.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="block.user_sectors",
        api_command="user-sectors",
        flat_command="tdx-get-user-sector",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.create_sector",
        domain="block",
        description="Create a custom TongDaXin sector.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="block.create_sector",
        api_command="create-sector",
        flat_command="tdx-create-sector",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.delete_sector",
        domain="block",
        description="Delete a custom TongDaXin sector.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="block.delete_sector",
        api_command="delete-sector",
        flat_command="tdx-delete-sector",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.rename_sector",
        domain="block",
        description="Rename a custom TongDaXin sector.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="block.rename_sector",
        api_command="rename-sector",
        flat_command="tdx-rename-sector",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.clear_sector",
        domain="block",
        description="Clear a custom TongDaXin sector.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="block.clear_sector",
        api_command="clear-sector",
        flat_command="tdx-clear-sector",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.send_user_block",
        domain="block",
        description="Write symbols into a custom TongDaXin sector.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="block.send_user_block",
        api_command="send-user-block",
        flat_command="tdx-send-user-block",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.read_watchlist_snapshot",
        domain="block",
        description="Read one TongDaXin custom sector as a normalized watchlist snapshot.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="block.read_watchlist_snapshot",
        api_command="block-read-watchlist",
        flat_command="tdx-block-read-watchlist",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "block.sync_watchlist",
        domain="block",
        description="Synchronize a normalized watchlist into a TongDaXin custom sector with governed replace or merge semantics.",
        stability="beta",
        side_effect_level="local_state_mutating",
        manager_method="block.sync_watchlist",
        api_command="block-sync",
        flat_command="tdx-block-sync",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.format_data",
        domain="formula",
        description="Normalize kline payloads for TongDaXin formula execution.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.format_data",
        api_command="formula-format-data",
        flat_command="tdx-formula-format-data",
    ),
    _capability(
        "formula.set_data",
        domain="formula",
        description="Load formula runtime data from explicit payloads.",
        stability="stable",
        side_effect_level="local_state_mutating",
        manager_method="formula.set_data",
        api_command="formula-set-data",
        flat_command="tdx-formula-set-data",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.set_data_info",
        domain="formula",
        description="Load formula runtime data from runtime query inputs.",
        stability="stable",
        side_effect_level="local_state_mutating",
        manager_method="formula.set_data_info",
        api_command="formula-set-data-info",
        flat_command="tdx-formula-set-data-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.get_data",
        domain="formula",
        description="Read current formula runtime data.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.get_data",
        api_command="formula-get-data",
        flat_command="tdx-formula-get-data",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.zb",
        domain="formula",
        description="Execute indicator formula calculation.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.zb",
        api_command="formula-zb",
        flat_command="tdx-formula-zb",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.xg",
        domain="formula",
        description="Execute formula stock screen.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.xg",
        api_command="formula-xg",
        flat_command="tdx-formula-xg",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.exp",
        domain="formula",
        description="Execute expert-system style formula evaluation.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.exp",
        api_command="formula-exp",
        flat_command="tdx-formula-exp",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.process_mul_xg",
        domain="formula",
        description="Execute batch stock-screen formula workflow.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.process_mul_xg",
        api_command="formula-mul-xg",
        flat_command="tdx-formula-mul-xg",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.screen",
        domain="formula",
        description="Execute the stable provider-facing batch stock-screen contract.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="formula.screen",
        api_command="formula-screen",
        flat_command="tdx-formula-screen",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.process_mul_zb",
        domain="formula",
        description="Execute batch indicator formula workflow.",
        stability="stable",
        side_effect_level="read_only",
        manager_method="formula.process_mul_zb",
        api_command="formula-mul-zb",
        flat_command="tdx-formula-mul-zb",
        requires=["native_windows_python", "tqcenter"],
    ),
    # --- Group A: tqcenter bridge (send_message, send_file, send_bt_data) ---
    _capability(
        "runtime.send_message",
        domain="runtime",
        description="Send a text message to the TongDaXin client TQ strategy panel.",
        stability="stable",
        side_effect_level="live_side_effecting",
        manager_method="runtime.send_message",
        api_command="send-message",
        flat_command="tdx-send-message",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.send_file",
        domain="runtime",
        description="Send a file to the TongDaXin client for viewing in TQ data browser.",
        stability="stable",
        side_effect_level="live_side_effecting",
        manager_method="runtime.send_file",
        api_command="send-file",
        flat_command="tdx-send-file",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.send_bt_data",
        domain="runtime",
        description="Send backtest result data to the TongDaXin client.",
        stability="stable",
        side_effect_level="live_side_effecting",
        manager_method="runtime.send_bt_data",
        api_command="send-bt-data",
        flat_command="tdx-send-bt-data",
        requires=["native_windows_python", "tqcenter"],
    ),
    # --- Group B: documented-only functions ---
    _capability(
        "meta.get_relation",
        domain="meta",
        description="Get stock relation data from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="meta.get_relation",
        api_command="get-relation",
        flat_command="tdx-get-relation",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "meta.gb_info_by_date",
        domain="meta",
        description="Get stock board info by specific date from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="meta.gb_info_by_date",
        api_command="gb-info-by-date",
        flat_command="tdx-gb-info-by-date",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.get_pricevol",
        domain="market",
        description="Get price-volume data from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="market.get_pricevol",
        api_command="get-pricevol",
        flat_command="tdx-get-pricevol",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "market.get_trackzs_etf_info",
        domain="market",
        description="Get ETF tracking index info from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="market.get_trackzs_etf_info",
        api_command="get-trackzs-etf-info",
        flat_command="tdx-get-trackzs-etf-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.get_all",
        domain="formula",
        description="Get all available formula list from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="formula.get_all",
        api_command="formula-get-all",
        flat_command="tdx-formula-get-all",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "formula.get_info",
        domain="formula",
        description="Get specific formula info by name from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="formula.get_info",
        api_command="formula-get-info",
        flat_command="tdx-formula-get-info",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.print_to_tdx",
        domain="runtime",
        description="Export multi-group data to TongDaXin client for display.",
        stability="beta",
        side_effect_level="live_side_effecting",
        manager_method="runtime.print_to_tdx",
        api_command="print-to-tdx",
        flat_command="tdx-print-to-tdx",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "runtime.exec_to_tdx",
        domain="runtime",
        description="Execute a command or navigate to a URL in the TongDaXin client.",
        stability="beta",
        side_effect_level="live_side_effecting",
        manager_method="runtime.exec_to_tdx",
        api_command="exec-to-tdx",
        flat_command="tdx-exec-to-tdx",
        requires=["native_windows_python", "tqcenter"],
    ),
    # --- Group C: trading domain ---
    _capability(
        "trade.stock_account",
        domain="trade",
        description="Get trading account handle from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="trade.stock_account",
        api_command="stock-account",
        flat_command="tdx-stock-account",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "trade.order_stock",
        domain="trade",
        description="Submit a stock order via TongDaXin trading interface.",
        stability="beta",
        side_effect_level="live_side_effecting",
        manager_method="trade.order_stock",
        api_command="order-stock",
        flat_command="tdx-order-stock",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "trade.query_stock_orders",
        domain="trade",
        description="Query today's stock orders from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="trade.query_stock_orders",
        api_command="query-stock-orders",
        flat_command="tdx-query-stock-orders",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "trade.query_stock_positions",
        domain="trade",
        description="Query stock positions from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="trade.query_stock_positions",
        api_command="query-stock-positions",
        flat_command="tdx-query-stock-positions",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "trade.cancel_order_stock",
        domain="trade",
        description="Cancel a stock order via TongDaXin trading interface.",
        stability="beta",
        side_effect_level="live_side_effecting",
        manager_method="trade.cancel_order_stock",
        api_command="cancel-order-stock",
        flat_command="tdx-cancel-order-stock",
        requires=["native_windows_python", "tqcenter"],
    ),
    _capability(
        "trade.query_stock_asset",
        domain="trade",
        description="Query account asset info from TongDaXin.",
        stability="beta",
        side_effect_level="read_only",
        manager_method="trade.query_stock_asset",
        api_command="query-stock-asset",
        flat_command="tdx-query-stock-asset",
        requires=["native_windows_python", "tqcenter"],
    ),
]


def list_provider_capabilities() -> list[dict[str, Any]]:
    return copy.deepcopy(_CAPABILITY_REGISTRY)


def summarize_provider_capabilities(capabilities: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    rows = capabilities if capabilities is not None else list_provider_capabilities()
    stability_counts = Counter(str(item.get("stability", "")) for item in rows)
    side_effect_counts = Counter(str(item.get("side_effect_level", "")) for item in rows)
    domain_counts = Counter(str(item.get("domain", "")) for item in rows)
    return {
        "total": len(rows),
        "by_domain": {key: domain_counts[key] for key in sorted(domain_counts)},
        "by_stability": {key: stability_counts[key] for key in STABILITY_LEVELS if stability_counts[key]},
        "by_side_effect_level": {key: side_effect_counts[key] for key in SIDE_EFFECT_LEVELS if side_effect_counts[key]},
    }


def build_capability_discovery_payload() -> dict[str, Any]:
    capabilities = list_provider_capabilities()
    return {
        "capabilities": capabilities,
        "summary": summarize_provider_capabilities(capabilities),
        "grading": {
            "stability_levels": list(STABILITY_LEVELS),
            "side_effect_levels": list(SIDE_EFFECT_LEVELS),
        },
    }
